# Generated by Django 3.1.7 on 2021-09-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPost', models.CharField(max_length=100)),
                ('seguidor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'mensajes',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='Anonymous', max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.FileField(upload_to='template_project/static/uploads/')),
                ('text', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Seguidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguidor', models.CharField(max_length=100)),
                ('seguido', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seguidos',
            },
        ),
    ]
